Increase the number of generated transactions. Update custom flood config
NethermindEth/fb-builder pull request #2
Opened 2023-10-19 21:25 UTC by piwonskp

2023-10-19 22:33 UTC, cbermudez97 approved these changes
LGTM. Just some minor format differences in the `network_params.json` with some tab instead of spaces.

2023-10-20 13:33 UTC, OlegJakushkin requested changes
Why the increases?
Please update PR details, reasoning and documentation.

2023-10-24 12:54 UTC, piwonskp commented
Fixed @OlegJakushkin

2023-10-24 12:57 UTC, OlegJakushkin approved these changes

2023-10-24 12:58 UTC, merged